### ISSUE TITLE
Error: Invaild or corrupt jarfile mdb.jar

### ISSUE THREAD

**Issue by ghost** [VioletXF/MessengerBotDebugBridge#1]
If you try to run the mdb.jar file, you get an error: Invalid or corrupt jarfile mdb.jar. I don't know when I run it through Windows, but I'm using Ubuntu 20.04, and the command I run is java -jar mdb.jar. I don't solve this problem

**Comment by VioletXF** [comment]
This **library**  is not standalone, which means you can't execute jar file.

**Comment by ghost** [comment]
Hmm... Okay I understand Thanks, then close the issues
